# Generated by Django 5.0.1 on 2024-02-01 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_jogador_add_ons_jogador_buy_in_jogador_rebuys'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField(unique=True)),
                ('small', models.IntegerField()),
                ('big', models.IntegerField()),
            ],
        ),
    ]
