# Generated by Django 5.0.1 on 2024-02-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torneio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeTorneio', models.CharField(max_length=100)),
                ('jogadores_total', models.IntegerField()),
                ('jogadores_atual', models.IntegerField()),
                ('horario_intervalo', models.IntegerField()),
                ('buyin_valor', models.IntegerField()),
                ('rebuy_valor', models.IntegerField()),
                ('addon_valor', models.IntegerField()),
            ],
        ),
    ]
