# Generated by Django 5.0.1 on 2024-02-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_torneio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='torneio',
            name='horario_intervalo',
            field=models.DateTimeField(),
        ),
    ]
