# Generated by Django 5.0.1 on 2024-02-02 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_torneio_horario_intervalo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='torneio',
            old_name='nomeTorneio',
            new_name='nome_torneio',
        ),
    ]
