# Generated by Django 5.0.1 on 2024-02-02 12:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_nometorneio_torneio_nome_torneio'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneio',
            name='horario_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
