# Generated by Django 5.0.1 on 2024-02-12 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_torneio_horario_inicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneio',
            name='intervalo_ativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='torneio',
            name='tempo_blind_posintervalo',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='torneio',
            name='tempo_blind_preintervalo',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='torneio',
            name='tempo_intervalo',
            field=models.IntegerField(default=20),
        ),
    ]
