# Generated by Django 5.0.1 on 2024-02-12 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_jogador_fichasbonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='jogador',
            name='observacoes_pagamento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jogador',
            name='pago',
            field=models.CharField(choices=[('nao', 'Não'), ('sim', 'Sim'), ('parcial', 'Parcial')], default='nao', max_length=10),
        ),
    ]
